### PR TITLE
Stackize project

### PR DESCRIPTION
**Pull request by lcycon**
Separated from that previous PR. If you decide to include this, I'd be happy to sign on as a maintainer and [help submit SimpleIRC into one of Stackage's lts builds](https://github.com/fpco/stackage#add-your-package)!

### CODE REVIEW

**Comment by dom96** [comment]
I'm happy to add you as a contributor to this package if you wish :)

**Comment by lcycon** [comment]
Sure, sign me up!

**Comment by dom96** [comment]
Done :)

**Comment by lcycon** [comment]
I've updated this PR to build against the most recent stack LTS resolver. If you want to merge, build, and release a v0.3.2, I can start the process of getting the package included into stack!

CC #24

**Comment by dom96** [comment]
it's been a while, but I actually gave you contributor rights to this project back then. If you want to get this going feel free to do so :)

**Pull request closed without merging**
